import { Injectable } from '@angular/core';

import { ProgressService } from '../../core/presentation/services/progress.service';
import { IUser } from '../presentation/interfaces/user.interface';

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private users: IUser[] = [
    { id: 1, name: 'name01', lastname: 'lastname01' },
    { id: 2, name: 'name02', lastname: 'lastname02' },
    { id: 3, name: 'name03', lastname: 'lastname03' },
    { id: 4, name: 'name04', lastname: 'lastname04' },
    { id: 5, name: 'name05', lastname: 'lastname05' },
    { id: 6, name: 'name06', lastname: 'lastname06' },
    { id: 7, name: 'name07', lastname: 'lastname07' },
    { id: 8, name: 'name08', lastname: 'lastname08' },
    { id: 9, name: 'name09', lastname: 'lastname09' },
    { id: 10, name: 'name10', lastname: 'lastname10' },
    { id: 11, name: 'name11', lastname: 'lastname11' },
    { id: 12, name: 'name12', lastname: 'lastname12' },
    { id: 13, name: 'name13', lastname: 'lastname13' },
    { id: 14, name: 'name14', lastname: 'lastname14' },
    { id: 15, name: 'name15', lastname: 'lastname15' },
    { id: 16, name: 'name16', lastname: 'lastname16' },
    { id: 17, name: 'name17', lastname: 'lastname17' },
    { id: 18, name: 'name18', lastname: 'lastname18' },
    { id: 19, name: 'name19', lastname: 'lastname19' },
    { id: 20, name: 'name20', lastname: 'lastname20' },
    { id: 1, name: 'name01', lastname: 'lastname01' },
    { id: 2, name: 'name02', lastname: 'lastname02' },
    { id: 3, name: 'name03', lastname: 'lastname03' },
    { id: 4, name: 'name04', lastname: 'lastname04' },
    { id: 5, name: 'name05', lastname: 'lastname05' },
    { id: 6, name: 'name06', lastname: 'lastname06' },
    { id: 7, name: 'name07', lastname: 'lastname07' },
    { id: 8, name: 'name08', lastname: 'lastname08' },
    { id: 9, name: 'name09', lastname: 'lastname09' },
    { id: 10, name: 'name10', lastname: 'lastname10' },
    { id: 11, name: 'name11', lastname: 'lastname11' },
    { id: 12, name: 'name12', lastname: 'lastname12' },
    { id: 13, name: 'name13', lastname: 'lastname13' },
    { id: 14, name: 'name14', lastname: 'lastname14' },
    { id: 15, name: 'name15', lastname: 'lastname15' },
    { id: 16, name: 'name16', lastname: 'lastname16' },
    { id: 17, name: 'name17', lastname: 'lastname17' },
    { id: 18, name: 'name18', lastname: 'lastname18' },
    { id: 19, name: 'name19', lastname: 'lastname19' },
    { id: 20, name: 'name20', lastname: 'lastname20' },
    { id: 1, name: 'name01', lastname: 'lastname01' },
    { id: 2, name: 'name02', lastname: 'lastname02' },
    { id: 3, name: 'name03', lastname: 'lastname03' },
    { id: 4, name: 'name04', lastname: 'lastname04' },
    { id: 5, name: 'name05', lastname: 'lastname05' },
    { id: 6, name: 'name06', lastname: 'lastname06' },
    { id: 7, name: 'name07', lastname: 'lastname07' },
    { id: 8, name: 'name08', lastname: 'lastname08' },
    { id: 9, name: 'name09', lastname: 'lastname09' },
    { id: 10, name: 'name10', lastname: 'lastname10' },
    { id: 11, name: 'name11', lastname: 'lastname11' },
    { id: 12, name: 'name12', lastname: 'lastname12' },
    { id: 13, name: 'name13', lastname: 'lastname13' },
    { id: 14, name: 'name14', lastname: 'lastname14' },
    { id: 15, name: 'name15', lastname: 'lastname15' },
    { id: 16, name: 'name16', lastname: 'lastname16' },
    { id: 17, name: 'name17', lastname: 'lastname17' },
    { id: 18, name: 'name18', lastname: 'lastname18' },
    { id: 19, name: 'name19', lastname: 'lastname19' },
    { id: 20, name: 'name20', lastname: 'lastname20' },
    { id: 1, name: 'name01', lastname: 'lastname01' },
    { id: 2, name: 'name02', lastname: 'lastname02' },
    { id: 3, name: 'name03', lastname: 'lastname03' },
    { id: 4, name: 'name04', lastname: 'lastname04' },
    { id: 5, name: 'name05', lastname: 'lastname05' },
    { id: 6, name: 'name06', lastname: 'lastname06' },
    { id: 7, name: 'name07', lastname: 'lastname07' },
    { id: 8, name: 'name08', lastname: 'lastname08' },
    { id: 9, name: 'name09', lastname: 'lastname09' },
    { id: 10, name: 'name10', lastname: 'lastname10' },
    { id: 11, name: 'name11', lastname: 'lastname11' },
    { id: 12, name: 'name12', lastname: 'lastname12' },
    { id: 13, name: 'name13', lastname: 'lastname13' },
    { id: 14, name: 'name14', lastname: 'lastname14' },
    { id: 15, name: 'name15', lastname: 'lastname15' },
    { id: 16, name: 'name16', lastname: 'lastname16' },
    { id: 17, name: 'name17', lastname: 'lastname17' },
    { id: 18, name: 'name18', lastname: 'lastname18' },
    { id: 19, name: 'name19', lastname: 'lastname19' },
    { id: 20, name: 'name20', lastname: 'lastname20' },
    { id: 1, name: 'name01', lastname: 'lastname01' },
    { id: 2, name: 'name02', lastname: 'lastname02' },
    { id: 3, name: 'name03', lastname: 'lastname03' },
    { id: 4, name: 'name04', lastname: 'lastname04' },
    { id: 5, name: 'name05', lastname: 'lastname05' },
    { id: 6, name: 'name06', lastname: 'lastname06' },
    { id: 7, name: 'name07', lastname: 'lastname07' },
    { id: 8, name: 'name08', lastname: 'lastname08' },
    { id: 9, name: 'name09', lastname: 'lastname09' },
    { id: 10, name: 'name10', lastname: 'lastname10' },
    { id: 11, name: 'name11', lastname: 'lastname11' },
    { id: 12, name: 'name12', lastname: 'lastname12' },
    { id: 13, name: 'name13', lastname: 'lastname13' },
    { id: 14, name: 'name14', lastname: 'lastname14' },
    { id: 15, name: 'name15', lastname: 'lastname15' },
    { id: 16, name: 'name16', lastname: 'lastname16' },
    { id: 17, name: 'name17', lastname: 'lastname17' },
    { id: 18, name: 'name18', lastname: 'lastname18' },
    { id: 19, name: 'name19', lastname: 'lastname19' },
    { id: 20, name: 'name20', lastname: 'lastname20' },
  ];

  constructor(private readonly progressService: ProgressService) {}

  async getUsers(): Promise<IUser[]> {
    this.progressService.setStatusProgressBar(true);
    const randomTime = Math.floor(Math.random() * 20000) + 4000;
    await new Promise((resolve) => setTimeout(resolve, randomTime));
    this.progressService.setStatusProgressBar(false);
    return [...this.users];
  }
}
